export const booksSeed = [
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'SToaB2',
    name: 'Some Interesting Book',
    author: 'Some interesting awesome author',
    publHouse: 'some big publishing house',
    year: '2005',
    genre: 'drama',
    copies: 1301,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
  {
    code: 'AToaB2',
    name: 'Another Interesting Book',
    author: 'Another interesting awesome author',
    publHouse: 'another big publishing house',
    year: '2007',
    genre: 'drama',
    copies: 2302,
  },
];
export const usersSeed = [
  {
    username: 'andrei',
    password: 'pass',
    email: 'andrei@gmail.com',
    firstName: 'Andrei',
    lastName: 'Nicolae',
    phone: '+40770399130',
    isAdmin: false,
  },
  {
    username: 'andreiene',
    password: 'pass',
    email: 'andreiene77@gmail.com',
    firstName: 'Andrei',
    lastName: 'Ene',
    phone: '0770399130',
    isAdmin: true,
  },
  {
    username: 'admin',
    password: 'pass',
    email: 'admin@library.com',
    firstName: '',
    lastName: '',
    phone: '',
    isAdmin: true,
  },
];
export const actionsSeed = [];
